### ISSUE TITLE
不断弹出提示“指纹识别错误，等待几秒之后再重试“

### ISSUE THREAD

**Issue by cayden** [PopFisher/FingerprintRecognition#4]
在小米6手机上，不断弹出如题的提示。

**Comment by PopFisher** [comment]
小米上可能会跟它自己的指纹识别冲突了，你看下手机是不是开了指纹解锁

**Comment by cayden** [comment]
的确是 开了指纹解锁了。

**Comment by tiancili** [comment]
那应该怎么解决

**Comment by tiancili** [comment]
So how do I solve this problem？

**Comment by PopFisher** [comment]
双锁屏的问题确实难解，我们一般是选择性的支持指纹识别的，有些机器出现问题严重的话直接不支持。另外可以通过引导用户去关闭系统锁
