### ISSUE TITLE
onFailedRetry(int msgId) 参数好像是没用的?

### ISSUE THREAD

**Issue by shenpeibao** [PopFisher/FingerprintRecognition#5]
mFailedTimes也没判断次数？

**Comment by PopFisher** [comment]
嗯，没有使用，只是写了一个简单的demen，具体的应用场景，重试次数需要自己控制。另外那个msgId并不靠谱，有些厂商改过了，不跟官方一样，建议可以参考public void onAuthenticationHelp(int helpMsgId, CharSequence helpString)的第二个参数。这个厂商一般会根据具体的错误返回一些字符串。

**Comment by PopFisher** [comment]
感谢你的仔细阅读，我完善了一些代码小细节，你有需要自己同步一下
